### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by NejcZdovc** [james2doyle/atom-jquery-snippets#14]
Did you make mistake with new version? Because you bumped it to 11.0.0.

**Comment by james2doyle** [comment]
It's fine. There is a problem with Atom. When you try to publish, it bumps
the version automatically, even when the publish fails. It also commits
that version to a git tag. I find it a little annoying. At this point,
turning it back would not allow people to update properly.

**Comment by NejcZdovc** [comment]
I agree and yes that's annoying. Thx for the update

**Comment by james2doyle** [comment]
I'm considering making an issue on the Atom repo about not tagging the repo
until the publish has started. Having it tag before, creates the issue you
outlined here: crazy tags and confusing versions.

**Comment by NejcZdovc** [comment]
Yes until the publish has started and when publish is successful, because if publish failed you will still have the same problem.
